name: CI/CD Pipeline for JustOneClick Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            set -e
            if [ ! -d ~/workspace ]; then
              git clone https://github.com/nararyamdh/JustOneClick.git ~/workspace
            fi
            source ~/.venv/bin/activate
            pip install -r ~/packages/requirements.txt
            cd ~/workspace/joc_web_app
            python manage.py migrate --noinput
            sudo systemctl restart joc_gunicorn
            sudo systemctl restart nginx
          '
